# Generated by Django 5.0.3 on 2026-04-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_assignment_teamsubmission_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='grades_released',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teamsubmission',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teamsubmission',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
