# Generated by Django 5.0.3 on 2026-04-15 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_alter_customuser_role_developer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamsubmission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='team_submissions/'),
        ),
        migrations.CreateModel(
            name='SubmissionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='team_submissions/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='teams.teamsubmission')),
            ],
        ),
    ]
