# Generated by Django 5.0.3 on 2026-04-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_systempulse_systemerror'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
