# Generated by Django 5.0.3 on 2026-04-21 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemPulse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('OPERATIONAL', 'Operational'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical'), ('DOWN', 'Down')], default='OPERATIONAL', max_length=20)),
                ('latency', models.FloatField(help_text='Response time in ms')),
                ('info', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'teams_systempulse',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_team_size', models.IntegerField(default=4)),
            ],
            options={
                'verbose_name_plural': 'System Settings',
                'db_table': 'teams_systemsettings',
            },
        ),
        migrations.CreateModel(
            name='SystemError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=255)),
                ('stack_trace', models.TextField()),
                ('url', models.CharField(blank=True, max_length=255)),
                ('is_resolved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teams_systemerror',
                'ordering': ['-timestamp'],
            },
        ),
    ]
