# Generated by Django 5.0.3 on 2026-04-24 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auditlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemPulse',
        ),
    ]
