# Generated by Django 5.0.3 on 2026-04-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
