# Generated by Django 5.0.3 on 2026-04-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_email_notifications_student_linkedin_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='academic_year',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Khóa'),
        ),
    ]
