# Generated by Django 5.0.3 on 2026-04-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_student_academic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='role_description',
            field=models.TextField(blank=True, help_text='Detailed description of your role responsibilities.'),
        ),
        migrations.AlterField(
            model_name='student',
            name='academic_year',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Batch'),
        ),
    ]
