# Generated by Django 5.0.3 on 2026-04-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/teams/'),
        ),
    ]
